In [2]:
import numpy as np

In [3]:
#Create a numpy array from a python list

In [4]:
lst = [1,2,3,4,5,6,7,8,9,0]
array = np.array(lst)


In [5]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
#Create a matrix from a python list of lists

In [7]:
matrix = [[1,2,3],[4,5,6]]
matrix_np = np.array(matrix)

In [10]:
matrix_np



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Generate numpy arrays from a starting number to an end number(escluded). Step size = 1

In [13]:
vector1 = np.arange(0,100)
vector1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
#Generate numpy arrays from a starting number to an end number(escluded). Step size = 2

In [15]:
vector2 = np.arange(0,100,2)
vector2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
#Generate numpy arrays of just zeros (35 in this example). A vector is created in this example

In [26]:
zeros = np.zeros(35)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [28]:
#Generate numpy arrays of just zeros (35x35 in this example). A matrix is created in this example

In [30]:
zeros2 = np.zeros((35,35))
zeros2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
#Create evenly spaced numbers over an interval. In this example generate 5 numbers over the interval 0 and 10 included

In [34]:
linspace = np.linspace(0,10,5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#Create evenly spaced numbers over an interval. In this example generate 5 numbers over the interval 0 and 10 included
#and return step size

In [40]:
linspace2, stepsize = np.linspace(0,10,5,retstep=True)
linspace2
stepsize


2.5

In [42]:
#Create identity matrix

In [44]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#Create a matrix with ones on the diagonal and zeros elsewhere. In this example, a 2x3 matrix is created

In [50]:
ones_diagonal = np.eye(2,3)
ones_diagonal

array([[1., 0., 0.],
       [0., 1., 0.]])

In [52]:
#numpy.random is a module

In [57]:
# A random matrix 3x2 is created with values 0..1 extracted from a uniform distribution

In [56]:
rand = np.random.rand(3,2)
rand

array([[0.19337307, 0.76924032],
       [0.23867349, 0.05069432],
       [0.49337584, 0.90559019]])

In [59]:
#The function randn of the module numpy.random works as rand but extracts numbers from a standard normal distribution

In [60]:
#The function randint returns one or more random integers in a given interval. In the example an array of 10 random integers
# is created

In [62]:
random_int = np.random.randint(0,100,10)
random_int


array([30,  7, 29, 25, 50, 38, 32, 26, 20, 10])

In [64]:
#How to reshape a vector or matrix with the reshape function

In [69]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
arr = arr.reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
#How to find the max, min values and their indexes

In [80]:
random_arr = np.random.randint(0,100,size = 100)
random_arr

array([55, 92, 65, 84, 99,  4, 21, 32, 43, 77, 40, 77, 69, 54, 92, 49, 49,
       80, 31,  5, 51, 81, 56, 24, 74, 34,  8, 88, 64, 41,  0, 33, 18, 42,
       83, 93, 31,  3, 79, 83,  1, 90, 52, 88, 99, 53, 62, 48, 25, 21, 29,
       19, 81, 72, 92, 23, 39, 41, 62, 72, 98, 18, 98, 68, 82, 68, 55, 89,
       40, 40, 44, 64, 84, 61,  8, 84, 41, 55, 85, 91, 44, 38, 51, 84, 42,
       44, 79, 72, 65, 66,  8,  6, 35, 20, 12, 66, 84, 48, 18, 69])

In [81]:
#Get max number

In [83]:
mx = random_arr.max()
mx

99

In [85]:
#Get min number

In [87]:
mn = random_arr.min()
mn

0

In [88]:
#Get index max number

In [91]:
index_mx = random_arr.argmax()
mx = random_arr[index_mx]
mx

99

In [92]:
#Get index min 

In [96]:
index_mn = random_arr.argmin()
mn = random_arr[index_mn]
mn

0

type(random_arr)

In [98]:
#shape is an attribute of ndarray

In [106]:
random_arr.reshape(10,10).shape

(10, 10)

In [108]:
#Extract dtype of the array

In [110]:
random_arr.dtype

dtype('int32')

In [116]:
random_arr = np.arange(0,100,dtype="int64")
random_arr.dtype

dtype('int64')